import json
import logging
import time
import asyncio
from pathlib import Path
from .utxoracle_engine import UTXOracleEngine
from .telegram import TelegramAnnouncer

logger = logging.getLogger("witness.btc_logic")
STATE_FILE = Path("btc_price_state.json")

class PriceOracleLogic:
    """
    Core logic for the Witness BTC Price Oracle.
    Separates polling from announce logic and manages strict state persistence.
    """
    def __init__(self, config):
        self.config = config
        self.engine = UTXOracleEngine(config.bitcoin_rpc_urls)
        self.telegram = TelegramAnnouncer(config)
        self.last_known_height = 0
        self.last_price_cents = 0
        self.running = False
        self._load_state()

    def _load_state(self):
        """Restores the last known oracle state from disk."""
        if STATE_FILE.is_file():
            try:
                with STATE_FILE.open() as f:
                    data = json.load(f)
                self.last_known_height = data.get("height", 0)
                self.last_price_cents = data.get("price_cents_uint64", 0)
                logger.info(f"State restored: block {self.last_known_height}")
            except Exception as e:
                logger.warning(f"State file corrupt: {e}. Starting fresh.")

    def _save_state(self, state: dict):
        """Atomically saves the current oracle state."""
        tmp = STATE_FILE.with_suffix(".tmp")
        tmp.write_text(json.dumps(state, indent=2, ensure_ascii=False))
        tmp.replace(STATE_FILE)
        logger.info(f"State updated — Block {state['height']}")

    async def setup(self):
        """Initializes the engine and prepares the polling loop."""
        logger.info("Witness BTC Price Oracle initialized (Native UTXOracle v9.1)")
        self.running = True

    async def run(self):
        """Main asynchronous polling loop."""
        logger.info("Starting block polling loop...")
        while self.running:
            try:
                await self._poll()
            except Exception as e:
                logger.error(f"Loop error: {e}", exc_info=True)
            await asyncio.sleep(self.config.poll_interval_sec)

    async def stop(self):
        """Gracefully shuts down the oracle logic."""
        self.running = False
        await self.engine.close()

    async def _poll(self):
        """Checks for new blocks, executes consensus pricing, and seals the state."""
        height = await self.engine.provider.getblockcount()
        if height <= self.last_known_height:
            return

        try:
            # 1. Thermodynamic Extraction (Retrieving price AND data age)
            price_cents, blocks_scanned = await self.engine.get_price_for_consensus(height)
            
            # 2. Volatility Calculation (Delta)
            delta_pct = 0.0
            if self.last_price_cents > 0:
                delta_pct = round(((price_cents - self.last_price_cents) / self.last_price_cents) * 100, 3)

            # 3. Prepare raw L1 state
            state = {
                "height": height,
                "price_cents_uint64": price_cents,
                "data_age_blocks": blocks_scanned,  # CRITICAL FOR BTCDAI SECURITY
                "delta_pct": delta_pct,
                "timestamp": int(time.time()),
                "source": "UTXOracle_v9.1_Native"
            }
            
            # 4. Thermodynamic Seal (Binohash PoW Guard)
            # Guarantees to the IndexerClaw that this JSON was generated by the legitimate Oracle.
            from .binohash import compute_binohash
            logger.info(f"Applying Binohash seal (W={self.config.binohash_difficulty})...")
            bhash = compute_binohash(state, difficulty=self.config.binohash_difficulty)
            state["binohash"] = bhash
            
            # 5. Atomic Persistence & Telegram Broadcast
            self._save_state(state)
            await self.telegram.send_announcement_json(state)
            
            # 6. Update local tracking state
            self.last_known_height = height
            self.last_price_cents = price_cents
            
        except Exception as e:
            logger.error(f"Consensus failed for block {height}: {e}")
            # On failure (e.g., InsufficientEntropyError), advance height to avoid congestion
            # but do NOT update the state file. The Indexer will detect the stale state.
            self.last_known_height = height
